### ISSUE TITLE
Fix build on Windows

### ISSUE THREAD

**Issue by marco-bearzi-sonarsource** [SonarSource/sonar-analyzer-commons#216]
Tests fail when trying to build the project on Windows.
Probably due to usage of UNIX line separator

**Comment by quentin-jaquier-sonarsource** [comment]
I'm using Windows and I managed to build the project without any issues. Could you try again?

**Comment by marco-bearzi-sonarsource** [comment]
The issue is found at _ResourcesTest.java:32_ and is related to the way the line endings of the cloned repository are managed with Git. The carriage return in the test file _ResourcesTest.txt_ may be interpreted as `\r\n` and then compared to `\n` which always returns false. This issue is closed as independent from the code
