### ISSUE TITLE
Using the comment flag leads to false positves in SingleCharCharacterClassFinder

### ISSUE THREAD

**Issue by nils-werner-sonarsource** [SonarSource/sonar-analyzer-commons#217]
Adding the "comment" or "extended" flag to a regular expression causes all whitespaces to be removed. Whitespaces in character classes are excluded from this specification. However, our current implementation of the RegexLexer does not follow this exception and removes any whitespace. This leads to false positives in the SingleCharCharacterClassFinder, which cannot detect removed whitespaces.

One solution to solve this problem is to measure the size of the character class before raising an issue and check if there could be a removed whitespace character.

**Comment by Wohops** [comment]
Imported to Jira - [ACOMMONS-4](https://sonarsource.atlassian.net/browse/ACOMMONS-4)
