### ISSUE TITLE
Support absolute paths in FileProvider class

### ISSUE THREAD

**Issue by molar** [SonarSource/sonar-analyzer-commons#222]
Hello

I am experiencing some difficulties in getting the [python report sensor ](https://github.com/SonarSource/sonar-python/blob/6a88b322ab667e4956ad27e09348dccca1833d23/sonar-python-plugin/src/main/java/org/sonar/plugins/python/PythonReportSensor.java#L69) 

And traced it to this repo. 

Supporting absolute paths in the glob pattern, will allow me to not scan the entire repo, when i know the subfolder which contains all reports. 

For reference, it takes the sensor 
`INFO: Sensor Cobertura Sensor for Python coverage [python] (done) | time=459805ms`
To find 3 xml files all located in a subfolder. 

Thanks.

**Comment by quentin-jaquier-sonarsource** [comment]
Hello @molar ,

The recommended way to report such problems is to reach us through the [Sonar community forum](https://community.sonarsource.com/). By opening a thread there using the proper tags (Python, Coverage), you will directly reach the right people.

Best,
Quentin

**Comment by Wohops** [comment]
To be reopened in our community forum, if the issue still exists.
