### ISSUE TITLE
Support POSIX character classes for S5855

### ISSUE THREAD

**Issue by m-g-sonar** [SonarSource/sonar-analyzer-commons#223]
Currently, POSIX character classes are not supported by the common implementation of S5855.

There is a ticket on SONARPHP: https://jira.sonarsource.com/browse/SONARPHP-1239

Java POSIX character classes are however explicit and their support could be possible (https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html)

**Comment by Wohops** [comment]
Imported to Jira - [ACOMMONS-5](https://sonarsource.atlassian.net/browse/ACOMMONS-5)
