### ISSUE TITLE
Remove overlap between VerboseRegexFinder and SuperfluousCurlyBraceFinder

### ISSUE THREAD

**Issue by quentin-jaquier-sonarsource** [SonarSource/sonar-analyzer-commons#236]
```
"ab{0,0}c"
"ab{1,1}c"
```
These two regexes will report 2 issues each: one to simplify {N,N} into {N} and another to remove the unnecessary part.
We should remove the overlap between the two finders and do not suggest the simplification (VerboseRegexFinder) when the value is {0,0} or {1,1}.

**Comment by Wohops** [comment]
Imported in Jira - [ACOMMONS-6](https://sonarsource.atlassian.net/browse/ACOMMONS-6)
